"""Regenerate reports/ from results/. Numbers are never hand-edited.

Implements PROTOCOL §4's noise rule directly: a difference between two models at
a given N counts only if their seed-to-seed ranges do not overlap. Everything
narrower is printed as "within noise" and is not allowed to become a trend. The
rule lives in code because prose written by a model that has just seen an
encouraging number will find a way to call it suggestive.
"""
from __future__ import annotations

import json, pathlib, statistics, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
RESULTS, REPORTS = ROOT / "results", ROOT / "reports"


def load() -> list[dict]:
    out = []
    for p in RESULTS.glob("*.json"):
        if p.stem == "PENDING":
            continue
        try:
            out.append(json.loads(p.read_text()))
        except Exception:
            pass
    return out


def phase_state(rows: list[dict], grid: list[dict], phase: int) -> tuple[str, int, int, int]:
    ids = {c["id"] for c in grid if c["phase"] == phase}
    got = {r["id"] for r in rows if r["id"] in ids}
    failed = {r["id"] for r in rows if r["id"] in ids and r.get("status") == "failed"}
    if len(got) < len(ids):
        return "open", len(got), len(failed), len(ids)
    if len(failed) / max(len(ids), 1) > 0.20:
        return "inconclusive", len(got), len(failed), len(ids)
    return "closed", len(got), len(failed), len(ids)


def by_cell(rows, phase, model, n, key="rej_at_30"):
    vals = [r[key] for r in rows
            if r.get("status") == "ok" and r["phase"] == phase
            and r["model"] == model and r["n"] == n
            and isinstance(r.get(key), (int, float))]
    return vals


def compare(rows, phase, a, b, n) -> tuple[str, str]:
    """Return (verdict, detail) for model `a` vs `b` at size `n` under §4."""
    va, vb = by_cell(rows, phase, a, n), by_cell(rows, phase, b, n)
    if len(va) < 2 or len(vb) < 2:
        return "insufficient", f"{a}:{len(va)} {b}:{len(vb)} seeds"
    lo_a, hi_a = min(va), max(va)
    lo_b, hi_b = min(vb), max(vb)
    ma, mb = statistics.mean(va), statistics.mean(vb)
    if hi_a < lo_b:
        return f"{b} > {a}", f"{ma:.1f} vs {mb:.1f} (ranges disjoint)"
    if hi_b < lo_a:
        return f"{a} > {b}", f"{ma:.1f} vs {mb:.1f} (ranges disjoint)"
    return "within noise", f"{ma:.1f} vs {mb:.1f} (ranges overlap — not a gap)"


def main() -> None:
    grid = json.loads((ROOT / "experiments/grid.json").read_text())
    rows = load()
    REPORTS.mkdir(exist_ok=True)
    lines = ["# Results", "",
             "Generated by `tools/report.py`. Do not edit — regenerate instead.", ""]

    for phase in sorted({c["phase"] for c in grid}):
        state, got, failed, total = phase_state(rows, grid, phase)
        lines += [f"## Phase {phase}", "",
                  f"- cells: {got}/{total} returned, {failed} failed",
                  f"- state: **{state}**", ""]

        if state == "open":
            lines += ["Metrics withheld until the phase closes (PROTOCOL §5).", ""]
            continue
        if state == "inconclusive":
            lines += ["More than 20% of cells failed. Reported as inconclusive; the "
                      "surviving cells are not analysed (PROTOCOL §5).", ""]
            continue

        if phase == 1:
            lines += ["Equivariant (M3) vs augmented baseline (M1), by training-set size.",
                      "", "| N | verdict | detail |", "|---|---|---|"]
            for n in sorted({c["n"] for c in grid if c["phase"] == phase}):
                v, d = compare(rows, phase, "M1", "M3", n)
                lines.append(f"| {n:,} | {v} | {d} |")
            lines.append("")

    (REPORTS / "results.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {REPORTS / 'results.md'}")
    print("\n".join(lines[:14]))


if __name__ == "__main__":
    main()
