"""One turn of the autonomous loop: collect, dispatch, close a phase if it is done.

Designed to be called repeatedly and to be safe when nothing has changed. Every
decision it makes is mechanical; the moment a decision would require judgement it
stops and says so rather than choosing.

Exit codes:
    0  ran normally (work done or nothing to do)
    3  stopped and wants a human — reason on stdout
"""
from __future__ import annotations

import argparse, json, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def sh(*cmd: str) -> tuple[int, str]:
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    return r.returncode, (r.stdout + r.stderr).strip()


def phase_counts(phase: int) -> tuple[int, int, int]:
    grid = json.loads((ROOT / "experiments/grid.json").read_text())
    ids = {c["id"] for c in grid if c["phase"] == phase}
    done = failed = 0
    for p in (ROOT / "results").glob("*.json"):
        if p.stem == "PENDING" or p.stem not in ids:
            continue
        try:
            d = json.loads(p.read_text())
        except Exception:
            continue
        done += 1
        failed += d.get("status") == "failed"
    return done, failed, len(ids)


def checkpoint(phase: int, done: int, failed: int, total: int, *, push: bool) -> None:
    """Commit progress every turn rather than only when the phase closes.

    A grid runs for hours; committing only at the end puts every intermediate
    result at the mercy of a dropped session or an exhausted quota. Empty commits
    are skipped, so a quiet turn leaves no trace.
    """
    sh("git", "add", "results", "reports")
    code, _ = sh("git", "diff", "--cached", "--quiet")
    if code == 0:
        print("checkpoint: no change")
        return
    code, out = sh("git", "commit", "-m",
                   f"Phase {phase} progress: {done}/{total} cells ({failed} failed)\n\n"
                   f"Checkpoint written by tools/tick.py.\n\n"
                   f"Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>")
    if code == 0:
        if push:
            sh("git", "push", "origin", "main")
        print(f"checkpoint committed{' and pushed' if push else ''}")
    else:
        print(f"checkpoint failed: {out.splitlines()[0] if out else '?'}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--phase", type=int, default=1)
    ap.add_argument("--limit", type=int, default=2)
    ap.add_argument("--epochs", type=int, default=12)
    ap.add_argument("--no-push", action="store_true")
    a = ap.parse_args()

    print("— collect —")
    _, out = sh(sys.executable, "tools/collect.py")
    print(out)

    done, failed, total = phase_counts(a.phase)
    print(f"\nphase {a.phase}: {done}/{total} returned, {failed} failed")

    # Stopping rule, checked before dispatching anything further: continuing to
    # burn GPU quota on a phase that is already inconclusive helps nobody.
    if total and failed / total > 0.20:
        print(f"\nSTOP: {failed}/{total} cells failed (>20%). PROTOCOL §5 makes this "
              f"phase inconclusive. Not dispatching further cells; a human should "
              f"look at the failure reasons before anything else runs.")
        return 3

    if done < total:
        print("\n— dispatch —")
        _, out = sh(sys.executable, "tools/submit.py", "--phase", str(a.phase),
                    "--limit", str(a.limit), "--epochs", str(a.epochs))
        print(out)
        checkpoint(a.phase, done, failed, total, push=not a.no_push)
        return 0

    # Phase complete.
    print(f"\n— phase {a.phase} closed —")
    _, out = sh(sys.executable, "tools/report.py")
    print(out)

    if not a.no_push:
        sh("git", "add", "results", "reports")
        code, out = sh("git", "commit", "-m",
                       f"Phase {a.phase} results ({done - failed} ok, {failed} failed)\n\n"
                       f"Generated by tools/tick.py. Numbers regenerated from results/ by "
                       f"tools/report.py; no hand-edited values.\n\n"
                       f"Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>")
        if code == 0:
            sh("git", "push", "origin", "main")
            print("committed and pushed")

    print(f"\nNEXT: phase {a.phase} needs the result-auditor before any prose is written "
          f"about it. Run /audit {a.phase}. The loop does not interpret results.")
    return 3


if __name__ == "__main__":
    sys.exit(main())
